### ISSUE TITLE
[BUG] 生成的 EPUB 不符合 EPUB 标准

### ISSUE THREAD

**Issue by yingziwu** [transky-book/transky#42]
问题使用 [epubcheck](https://github.com/w3c/epubcheck) 检查 [v1.0.0 release](https://github.com/transky-book/transky/releases/tag/v1.0.0) 所附带的 epub 文件，发现了众多错误（ERROR）。

## 详细日志

[transky-1.0.0.epub-epubcheck.log](https://github.com/transky-book/transky/files/14779210/transky-1.0.0.epub-epubcheck.log)

#### ERROR(OPF-060)： `OEBPS/illustrations/cover.jpg` 被添加至 ZIP 文件两次而不是一次

```console
$ zipdetails transky-1.0.0.epub | grep "OEBPS/illustrations/cover.jpg"      
03A2F39 Filename              'OEBPS/illustrations/cover.jpg'
146B0AB Filename              'OEBPS/illustrations/cover.jpg'
2DDAD1A Filename              'OEBPS/illustrations/cover.jpg'
2DDB002 Filename              'OEBPS/illustrations/cover.jpg'
```

解决办法：创建 ZIP 文件时只添加 `OEBPS/illustrations/cover.jpg`  一次。

#### ERROR(RSC-005)： `content.opf` 文件中 `id`、`idref` 属性不符合 XML 要求

![ERROR(OPF-074)](https://github.com/transky-book/transky/assets/22741471/5b77b522-2c7c-4f63-9e0e-70c5c0c5e141)

`id`、`idref` 属性的首字母不能是数字。

> **[Validity constraint: ID](https://www.w3.org/TR/xml/#id)**
>
>Values of type ID MUST match the [Name](https://www.w3.org/TR/xml/#NT-Name) production. A name MUST NOT appear more than once in an XML document as a value of this type; i.e., ID values MUST uniquely identify the elements which bear them.

> The first character of a [Name](https://www.w3.org/TR/xml/#NT-Name) MUST be a [NameStartChar](https://www.w3.org/TR/xml/#NT-NameStartChar), and any other characters MUST be [NameChars](https://www.w3.org/TR/xml/#NT-NameChar); this mechanism is used to prevent names from beginning with European (ASCII) digits or with basic combining characters.

>- [4]   	NameStartChar	   ::=   	":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
>- [4a]   	NameChar	   ::=   	[NameStartChar](https://www.w3.org/TR/xml/#NT-NameStartChar) | "-" | "." | [0-9] | #xB7 | [#x0300-#x036F] | [#x203F-#x2040]
>- [5]   	Name	   ::=   	[NameStartChar](https://www.w3.org/TR/xml/#NT-NameStartChar) ([NameChar](https://www.w3.org/TR/xml/#NT-NameChar))*

解决办法：`id`、`idref` 属性的首字母改为字母开头。

#### ERROR(OPF-074)：`content.opf` 文件中 `OEBPS/illustrations/cover.jpg` 出现了两次

`OEBPS/illustrations/cover.jpg` 在 `content.opf` 文件第771行、第781行出现，总共出现了两次。

![ERROR(OPF-074)](https://github.com/transky-book/transky/assets/22741471/2ef83899-081d-41e8-93ea-21f806455af2)

解决办法：移除重复项。

-----------------------------

### 额外建议

EPUB 2.0.1 发布于2009年，2011年就被 EPUB 3.0 所取代。

EPUB 2.0 已经过时了，而且不再被积极维护。

建议直接基于最新的 [EPUB 3.3 标准](https://www.w3.org/TR/epub/) 创建 epub 文件。

**Comment by Cryolitia** [comment]
closed by #45
