### ISSUE TITLE
有计划接入gitalk吗？

### ISSUE THREAD

**Issue by nailiable** [transky-book/transky#67]
如题，提供一个评论的空间。

**Comment by Cryolitia** [comment]
中華人民共和國《互聯網跟帖評論服務管理規定》（http://big5.www.gov.cn/gate/big5/www.gov.cn/xinwen/2022-11/16/content_5727349.htm）對提供、使用跟帖評論服務的網站提出了極其嚴苛且我們不能接受的要求，如：後臺實名、先審後發。即使我們的全部服務架構都不依賴於中國大陸境內的基礎網絡設施，但是提供這一服務依然會大幅提升我們被中國大陸ISP封鎖的概率，降低我們服務的可達性。這對我們而言是不可接受的風險。
        同時，根據［數據刪除］，Project Trans 沒有經驗也不善於參與社區的運營，故不應參與社區的運營，本決議已經［5級安全權限］一致通過。
跨兒們可以訪問我們的友情鏈接（https://mtf.wiki/zh-cn/docs/friendship/）欄目並加入其中的第三方羣組，您也可以在完善自身網站及管理條例後申請添加友情鏈接。

——节选自星历1013年仙舟罗浮三余书肆出版《MtF.wiki之外的往事 卷IX 读者来信辑》
