### ISSUE TITLE
03/226~227 逻辑问题

### ISSUE THREAD

**Issue by WindowsMEMZ** [transky-book/transky#73]
按照`226·停电`中所述：苏雨晴在黑暗中根本看不见路：

> “唔……对了，曲奇呢……”苏雨晴自言自语地说着，扭头四下看去，但是外面一片漆黑，家里又因为停电没有灯光，所以什么也看不见，可谓是名副其实的伸手不见五指的黑暗。
>
> 她其实挺佩服在这样黑暗的空间中，也能在房间里行走自如的张思凡他们的。

但在227节最后，苏雨晴能直接走进卫生间：

> “我……”苏雨晴有些后悔刚才自己说大话了，这会儿却又不好意思说自己没说过，她可不像张思凡，有那么厚的脸皮，于是她一咬牙，从沙发上站了起来，大义凛然地说道，“去就去，谁怕谁嘛！”
>
> “加油。”张思凡一边鼓掌，一边幸灾乐祸地说道，一副唯恐天下不乱的样子。
>
> “嘁，有什么好怕的嘛。”苏雨晴给自己壮着胆子，然后半信半疑地走进了卫生间里。

此处应该是逻辑问题，不过也或许是我漏掉了什么或没理解对，请多多指点。

**Comment by WindowsMEMZ** [comment]
> 于是苏雨晴就下了床，一只手和林夕晨牵着，另一只手则抱着曲奇，摸索着朝客厅里走去。
> 
> 明明在平时只是几秒钟的路程，今天却感觉是那样的漫长。
> 
> 苏雨晴好几次都差点撞到墙上，还好抱着有夜视能力的曲奇，每当快撞到东西的时候，它就会短促地连叫好几声，然后用毛茸茸的尾巴使劲扫着她的脸颊。
> 
> 短短几秒钟的路，走了整整五分钟。

从这几段可以看出，苏雨晴是确实看不清的

**Comment by epifirumu** [comment]
个人认为苏雨晴“能直接走进卫生间”是合理的，理由如下：

1. 视觉不是在房间中活动的必要条件。张思凡ta们仍然能在房间中行走说明在黑暗中活动其实是可行的，经常住在家里熟悉环境的话可以靠记忆与空间感知能力大概地行动，此外触觉（例如扶着墙）、声音（例如曲奇的叫声、同伴们聊天的嗓音）也能辅助定位。

   > “唔……对了，曲奇呢……”苏雨晴自言自语地说着，扭头四下看去，但是外面一片漆黑，家里又因为停电没有灯光，所以什么也看不见，可谓是名副其实的伸手不见五指的黑暗。
   >
   > 她其实挺佩服在这样黑暗的空间中，也能在房间里行走自如的张思凡他们的。



2. 苏雨晴的“碰壁”实际上为她熟悉环境做了准备，在有经验的情况下，后文中她在房间里活动只会更顺利。

   > 苏雨晴好几次都差点撞到墙上，还好抱着有夜视能力的曲奇，每当快撞到东西的时候，它就会短促地连叫好几声，然后用毛茸茸的尾巴使劲扫着她的脸颊。
   >
   > 短短几秒钟的路，走了整整五分钟。




3. 方莜莜使用手机照亮了房间。

   > “坐我边上吧。”方莜莜摸索了一会儿，把陷进沙发夹缝里的手机拿了出来，摁了一下按键，顿时冒出了一圈朦胧的亮光。
   >
   > 手机的光在平时基本没有感觉，可在这黑暗的环境中，却觉得那样明亮，就像是一盏指路明灯一般。




4. 人在逞能与恐惧的时候激发出更大的潜力是常见且合理的。

   > “诶……我……我不去……”虽然对张思凡的这个故事一点都不信，但苏雨晴还是不敢一个人走到卫生间里去。
   >
   > “小晴刚才不是说不怕的嘛？”张思凡促狭地笑了起来，故意用激将法刺激她，“你的胆子不会比老鼠还小吧？”
   >
   > “我……”苏雨晴有些后悔刚才自己说大话了，这会儿却又不好意思说自己没说过，她可不像张思凡，有那么厚的脸皮，于是她一咬牙，从沙发上站了起来，大义凛然地说道，“去就去，谁怕谁嘛！”



5. 合租房布局简单（“整体布局是长方形的形状” “中间就是客厅” “卫生间比较大” ）。

   02\108.md

   > 这是一间合租房，房子总共有一百五十多平米，被房东隔出了六个房间，可以分开租住，也可以一伙人一起租下来。
   >
   > 中间的是客厅，卫生间只有一个，比较麻烦，好在卫生间比较大，同时两个人一起洗漱应该是问题不大。

   02\110.md

   > 这个合租房的整体布局是长方形的形状，从正门进去，两侧就有两间房间，再往里走，左手边有一个房间，右手边是一个小阳台，以及一个比前面的房间稍微小一点的房间，走到底是卫生间，卫生间里有两个马桶，毕竟是合租房，房东肯定考虑到了卫生间不够用的情况，这样子最起码还能缓解一些问题。
   >
   > 卫生间的两边是两间小房间，而左边的小房间稍小一点，并且紧挨着厨房……

   
综上所述，苏雨晴能在黑暗能直接走进卫生间的确是合理的，至少绝不是不可能的。在这片小说是文学作品而非严谨的、解释性质的说明文的情况下，这样的情节其实是完全可以接受的。

**Comment by WindowsMEMZ** [comment]
好的，谢谢解答
